site_name: AII Guidance
theme:
  name: material
  palette:
    - scheme: default      # light mode
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate        # dark mode
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
    - media: "prefers-color-scheme: dark)"
      scheme: slate
nav:
  - Home: index.md
  - Terms & Sources: terms.md
  - Process Walkthrough: processwalkthrough.md
extra_css:
  - stylesheets/neom.css
plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
markdown_extensions:
  - attr_list
  - abbr
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.blocks.caption
  - pymdownx.keys
  - pymdownx.tabbed
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
      
  
  
