site_name: AII Guidance
theme:
  name: material
  palette:
    - scheme: default      # light mode
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate        # dark mode
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
    - media: "prefers-color-scheme: dark)"
      scheme: slate
  # Documentation & Theme
  custom_dir: 'theme'
nav:
  - Home: index.md
  - Terms & Sources: terms.md
  - Process Walkthrough: processwalkthrough.md
extra_css:
  - stylesheets/neom.css
markdown_extensions:
  - attr_list
  - abbr
  - lightgallery
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.blocks.caption
  - pymdownx.keys
  - pymdownx.tabbed
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
      
  
  
