site_name: AII Guidance
theme:
  name: material
  palette:
    - scheme: default      # light mode
      primary: custom
      accent: custom
    - scheme: slate        # dark mode
      primary: custom
      accent: custom
nav:
  - Home: index.md
  - Terms & Sources: terms.md
extra_css:
  - stylesheets/neom.css
markdown_extensions:
  - attr_list
